version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenwiz_raw_data
    tables:
      - name: sales
        description: greenwiz_raw_sales_data order_id and the included products_id
        identifier: raw_gz_sales
        columns:
          - name: date_date
            description: date_of_order
        tests:
          - unique:
               column_name: "(orders_id || '_' || pdt_id)"
                
      - name: ship
        description: shippings_cost of the order_id
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
      - name: product
        description: purchase_cost of the product_id
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: Primary Key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: price paid for product

models:
  - name: int_sales_margin
    tests:
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - Purchase_cost
            - date_date
            - revenue
            - quantity
  - name: stg_raw_product
  - name: stg_raw_sales
  - name: stg_raw_ship
    description: margin calculation per order line / product sale
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
  - name: int_orders_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order
      - name: quantity
        description: sum of quantity per order
  - name: int_orders_operational
    description: operational margin calculation per order
    columns:
      - name: operational_margin 
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
  - name: finance_days
    description: finance calculation per days
  - name: int_orders_margin
    description: margin calculation per order
    columns:
      - name: order_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order
      - name: quantity
        description: sum of quantity per order

